/**
 * Typed IPC client. Every command and payload type comes from the Rust side
 * (src/bindings is generated by ts-rs), so the contract is checked at compile
 * time. Outside Tauri (plain browser preview, tests) a mock backend answers.
 */
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

import type { AppInfo } from "../bindings/AppInfo";
import type { AppInfoResponse } from "../bindings/AppInfoResponse";
import type { CommandError } from "../bindings/CommandError";
import type { ContextEvent } from "../bindings/ContextEvent";
import type { Diagnostics } from "../bindings/Diagnostics";
import type { EngineStatus } from "../bindings/EngineStatus";
import type { ExclusionKind } from "../bindings/ExclusionKind";
import type { ExclusionRule } from "../bindings/ExclusionRule";
import type { HealthReport } from "../bindings/HealthReport";
import type { ModelOption } from "../bindings/ModelOption";
import type { ModelPricing } from "../bindings/ModelPricing";
import type { PaletteApplyRequest } from "../bindings/PaletteApplyRequest";
import type { PaletteApplyResult } from "../bindings/PaletteApplyResult";
import type { PaletteContext } from "../bindings/PaletteContext";
import type { PaletteRunRequest } from "../bindings/PaletteRunRequest";
import type { PaletteRunResult } from "../bindings/PaletteRunResult";
import type { PermissionState } from "../bindings/PermissionState";
import type { PermissionStatus } from "../bindings/PermissionStatus";
import type { ProviderStatus } from "../bindings/ProviderStatus";
import type { Settings } from "../bindings/Settings";
import type { UsageResponse } from "../bindings/UsageResponse";

export function inTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/** Normalizes anything thrown by a command into a CommandError. */
export function toCommandError(error: unknown): CommandError {
  if (error && typeof error === "object" && "message" in error && "code" in error) {
    const e = error as CommandError;
    return { code: e.code, message: e.message, fields: e.fields ?? [] };
  }
  return { code: "unknown", message: typeof error === "string" ? error : "Something went wrong.", fields: [] };
}

export function errorMessage(error: unknown): string {
  return toCommandError(error).message;
}

async function call<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  try {
    if (inTauri()) return await invoke<T>(command, args);
    // Browser preview / tests: the mock backend is loaded only when needed.
    const { mockInvoke } = await import("./mock");
    return await mockInvoke<T>(command, args);
  } catch (error) {
    throw toCommandError(error);
  }
}

export const api = {
  appInfo: () => call<AppInfoResponse>("get_app_info"),
  settings: () => call<Settings>("get_settings"),
  saveSettings: (settings: Settings) => call<Settings>("save_settings", { settings }),
  providerStatus: () => call<ProviderStatus>("get_provider_status"),
  setApiKey: (key: string) => call<ProviderStatus>("set_api_key", { key }),
  clearApiKey: () => call<ProviderStatus>("clear_api_key"),
  testConnection: (key?: string) => call<HealthReport>("test_connection", { key: key ?? null }),
  listModels: (refresh = false) => call<ModelOption[]>("list_models", { refresh }),
  usage: () => call<UsageResponse>("get_usage_dashboard"),
  listPricing: () => call<ModelPricing[]>("list_pricing"),
  savePricing: (pricing: ModelPricing) => call<ModelPricing[]>("save_pricing", { pricing }),
  deletePricing: (id: number) => call<ModelPricing[]>("delete_pricing", { id }),
  resetPricing: () => call<ModelPricing[]>("reset_pricing"),
  clearUsageHistory: () => call<number>("clear_usage_history"),
  clearContext: () => call<void>("clear_context"),
  resetLocalData: () => call<Settings>("reset_local_data"),
  listExclusions: () => call<ExclusionRule[]>("list_exclusions"),
  addExclusion: (kind: ExclusionKind, pattern: string, displayName: string) =>
    call<ExclusionRule[]>("add_exclusion", { kind, pattern, displayName }),
  removeExclusion: (id: number) => call<ExclusionRule[]>("remove_exclusion", { id }),
  runningApps: () => call<AppInfo[]>("list_running_apps"),
  alwaysExcluded: () => call<string[]>("get_always_excluded"),
  recentActivity: (limit = 100) => call<ContextEvent[]>("get_recent_activity", { limit }),
  permissionStatus: () => call<PermissionStatus>("get_permission_status"),
  requestAccessibility: () => call<PermissionState>("request_accessibility_permission"),
  openAccessibilitySettings: () => call<void>("open_accessibility_settings"),
  diagnostics: () => call<Diagnostics>("get_diagnostics"),
  copyDiagnostics: () => call<string>("copy_diagnostics"),
  setPaused: (minutes: number | null) => call<Settings>("set_paused", { minutes }),
  completeOnboarding: () => call<Settings>("complete_onboarding"),
  engineStatus: () => call<EngineStatus>("get_engine_status"),
  paletteContext: () => call<PaletteContext>("palette_context"),
  paletteRun: (request: PaletteRunRequest) => call<PaletteRunResult>("palette_run", { request }),
  paletteCancel: () => call<void>("palette_cancel"),
  paletteApply: (request: PaletteApplyRequest) => call<PaletteApplyResult>("palette_apply", { request }),
  paletteClose: (reactivate: boolean) => call<void>("palette_close", { reactivate }),
  paletteOpenMain: (section: string) => call<void>("palette_open_main", { section }),
  overlayReady: (seq: number, width: number, height: number) => call<void>("overlay_ready", { seq, width, height }),
};

/** Subscribes to a backend event; returns an unsubscribe function. */
export async function subscribe<T>(event: string, handler: (payload: T) => void): Promise<UnlistenFn> {
  if (!inTauri()) {
    const { mockListen } = await import("./mock");
    return mockListen<T>(event, handler);
  }
  return listen<T>(event, (e) => handler(e.payload));
}
