// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broad application category.
 */
export type AppCategory = "email" | "chat" | "ai_assistant" | "ide" | "terminal" | "notes" | "browser" | "launcher" | "password_manager" | "mote" | "other";
