// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsPlatform } from "./OsPlatform";

export type AppInfoResponse = { version: string, identifier: string, platform: OsPlatform, arch: string, dataDir: string, logDir: string, };
