// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An application as seen by the OS.
 */
export type AppInfo = { 
/**
 * Stable identifier: the bundle identifier on macOS (`com.tinyspeck.slackmacgap`),
 * the lowercase executable name on Windows (`slack.exe`).
 */
id: string, 
/**
 * Display name (`Slack`).
 */
name: string, pid: number | null, };
