// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClipboardKind = "empty" | "url" | "path" | "json" | "stack_trace" | "email" | "code" | "short_text" | "text";
