// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsError } from "./SettingsError";

export type CommandError = { 
/**
 * Stable machine-readable code.
 */
code: string, 
/**
 * Actionable message for the user.
 */
message: string, 
/**
 * Field-level validation problems, when `code` is `validation`.
 */
fields: Array<SettingsError>, };
