// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletionSettings = { enabled: boolean, 
/**
 * Pause after the last change before a completion is requested.
 */
debounceMs: number, 
/**
 * Minimum text length before the caret.
 */
minChars: number, 
/**
 * Upper bound on suggestion length.
 */
maxWords: number, 
/**
 * Minimum time between two completion requests.
 */
minIntervalMs: number, inConversations: boolean, inPrompts: boolean, inNotes: boolean, inUnknown: boolean, };
