// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something Mote can do with copied content.
 */
export type ContextAction = "create_coding_task" | "analyze_issue" | "debug_error" | "explain_code" | "summarize" | "draft_response" | "create_prompt";
