// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextSettings = { 
/**
 * Suggest using recently copied content when it looks relevant.
 */
contextualSuggestions: boolean, 
/**
 * How long copied text stays available to Mote (memory only).
 */
clipboardTtlSecs: number, 
/**
 * Allow a model call when local signals cannot classify the context.
 */
aiClassification: boolean, };
