// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppCategory } from "./AppCategory";
import type { ClipboardKind } from "./ClipboardKind";
import type { Feature } from "./Feature";
import type { InputRole } from "./InputRole";
import type { IntentKind } from "./IntentKind";

/**
 * A timestamped context event.
 */
export type ContextEvent = { timestamp: string, 
/**
 * `macos`, `windows` or `mote`.
 */
source: string, } & ({ "type": "application_changed", from: string | null, to: string, category: AppCategory, } | { "type": "input_focused", app: string, role: InputRole, } | { "type": "intent_classified", app: string, kind: IntentKind, confidence: number, } | { "type": "clipboard_changed", source_app: string | null, kind: ClipboardKind, char_count: number, } | { "type": "suggestion_shown", feature: Feature, } | { "type": "suggestion_accepted", feature: Feature, } | { "type": "suggestion_dismissed", feature: Feature, } | { "type": "paused", minutes: number | null, } | { "type": "resumed" });
