// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineStatus } from "./EngineStatus";
import type { HealthReport } from "./HealthReport";
import type { ModelAssignments } from "./ModelAssignments";
import type { PermissionStatus } from "./PermissionStatus";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";
import type { RequestOutcome } from "./RequestOutcome";

export type Diagnostics = { version: string, os: string, arch: string, provider: string, baseUrl: string, hasApiKey: boolean, models: ModelAssignments, unavailableModels: Array<string>, providerHealth: HealthReport | null, providerLimits: RateLimitSnapshot | null, permissions: PermissionStatus, clipboardObservation: boolean, textObservation: boolean, cloudAiEnabled: boolean, engine: EngineStatus, database: { schemaVersion: number, usageEvents: number, contextEvents: number, contextSessions: number, exclusions: number, pricingRows: number, sizeBytes: number | null } | null, databaseOk: boolean, databasePath: string, logDir: string, avgCompletionLatencyMs: number | null, completionRequests24h: number, lastRequest: RequestOutcome | null, };
