// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The engine's externally visible state.
 */
export type EngineState = "starting" | "active" | "idle" | "paused" | "disabled" | "excluded" | "needs_permission" | "secure_input" | "needs_api_key" | "cloud_disabled" | "offline" | "rate_limited";
