// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineState } from "./EngineState";
import type { IntentKind } from "./IntentKind";
import type { IntentSubtype } from "./IntentSubtype";
import type { LanguageLabel } from "./LanguageLabel";

export type EngineStatus = { state: EngineState, message: string | null, app: string | null, intent: IntentKind | null, subtype: IntentSubtype | null, intentConfidence: number | null, language: LanguageLabel | null, };
