// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Prompt-enhancement styles offered in the command palette.
 */
export type EnhanceStyle = "improve" | "precise" | "technical" | "structure" | "debug" | "research" | "explain" | "expand_context";
