// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an exclusion rule matches.
 */
export type ExclusionKind = "app" | "window_title";
