// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionKind } from "./ExclusionKind";

/**
 * A user-defined exclusion.
 */
export type ExclusionRule = { id: number, kind: ExclusionKind, 
/**
 * Bundle id / executable name / app name for `App`; keyword for `WindowTitle`.
 */
pattern: string, displayName: string, };
