// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";
import type { FeatureGroup } from "./FeatureGroup";

export type FeatureUsage = { feature: Feature, group: FeatureGroup, requests: number, totalTokens: number, estimatedCostUsd: number, 
/**
 * Share of all requests in the window (0..=1).
 */
share: number, avgLatencyMs: number | null, };
