// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Mote feature a request serves; recorded with every usage event.
 */
export type Feature = "inline_completion" | "writing_assistance" | "prompt_enhancement" | "intent_classification" | "context_analysis" | "translation" | "rewrite" | "command_interface";
