// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The dashboard's feature groups.
 */
export type FeatureGroup = "inline_completion" | "prompt_enhancement" | "writing_assistance" | "classification" | "context_analysis" | "other";
