// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type GeneralSettings = { 
/**
 * Master switch for all ambient assistance.
 */
assistanceEnabled: boolean, launchAtLogin: boolean, onboardingCompleted: boolean, 
/**
 * When set and in the future, Mote observes nothing until this time.
 */
pausedUntil: string | null, theme: Theme, 
/**
 * Check for, download and verify new versions in the background.
 */
autoUpdate: boolean, };
