// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAssignments } from "./ModelAssignments";

export type GroqSettings = { baseUrl: string, requestTimeoutMs: number, models: ModelAssignments, };
