// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a provider health check.
 */
export type HealthReport = { ok: boolean, latencyMs: number | null, modelsAvailable: number, 
/**
 * Configured models the provider does not offer.
 */
missingModels: Array<string>, 
/**
 * Actionable, user-facing message when `ok` is false.
 */
message: string | null, checkedAt: string, };
