// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of text control that has focus.
 */
export type InputRole = "text_area" | "text_field" | "search_field" | "combo_box" | "document" | "terminal" | "unknown";
