// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Finer-grained type of a conversation or prompt.
 */
export type IntentSubtype = "email" | "chat" | "professional_message" | "casual_message" | "coding" | "research" | "reasoning" | "general";
