// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of writing context.
 */
export type IntentKind = "conversation" | "prompt" | "code" | "command" | "note" | "search" | "form" | "unknown";
