// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyboardSettings = { 
/**
 * Opens the command palette from anywhere.
 */
commandPalette: string, 
/**
 * Shows the next suggestion while one is visible.
 */
nextSuggestion: string, 
/**
 * Shows the previous suggestion while one is visible.
 */
previousSuggestion: string, };
