// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The detected language variety.
 */
export type LanguageLabel = "english" | "hindi_latin" | "hinglish" | "mixed_english_hindi" | "marathi_latin" | "marathi_english" | "mixed_english_marathi" | "hindi_devanagari" | "marathi_devanagari" | "other" | "unknown";
