// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logical model roles. Each role is mapped to a concrete model in settings.
 */
export type ModelRole = "completion" | "classification" | "writing" | "reasoning";
