// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingSource } from "./PricingSource";

/**
 * List price of one model from a given date.
 */
export type ModelPricing = { id: number | null, provider: string, model: string, 
/**
 * USD per one million input tokens.
 */
inputCostPerMillion: number, 
/**
 * USD per one million output tokens.
 */
outputCostPerMillion: number, effectiveDate: string, source: PricingSource, };
