// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRole } from "./ModelRole";

export type ModelOption = { id: string, ownedBy: string | null, contextWindow: number | null, maxOutputTokens: number | null, inputCostPerMillion: number | null, outputCostPerMillion: number | null, 
/**
 * Roles this model is a sensible default for.
 */
recommendedFor: Array<ModelRole>, };
