// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which model serves each logical role.
 */
export type ModelAssignments = { completion: string, classification: string, writing: string, reasoning: string, 
/**
 * Used when a role's model is unavailable (removed or not accessible).
 */
fallback: string, };
