// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelUsage = { provider: string, model: string, requests: number, inputTokens: number, outputTokens: number, totalTokens: number, 
/**
 * `None` when Mote has no price for this model.
 */
estimatedCostUsd: number | null, avgLatencyMs: number | null, };
