// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operating system Mote runs on.
 */
export type OsPlatform = "macos" | "windows" | "other";
