// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverlayKind = "completion" | "correction" | "prompt_hint" | "context" | "notice";
