// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayView } from "./OverlayView";

/**
 * Payload for the overlay window.
 */
export type OverlayPayload = { seq: number, view: OverlayView, };
