// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayKind } from "./OverlayKind";
import type { Rect } from "./Rect";

/**
 * What the overlay should display.
 */
export type OverlayView = { kind: OverlayKind, 
/**
 * Completion remainder, corrected text, or chip title.
 */
text: string, 
/**
 * "completd → completed", or context actions.
 */
detail: string | null, index: number, count: number, 
/**
 * Caret rectangle in the platform's coordinate space.
 */
anchor: Rect | null, coordinateSpace: "logical_points" | "physical_pixels", 
/**
 * Key hint such as "Tab".
 */
acceptHint: string | null, };
