// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipboardPreview } from "./ClipboardPreview";
import type { ContextAction } from "./ContextAction";
import type { IntentKind } from "./IntentKind";
import type { IntentSubtype } from "./IntentSubtype";
import type { LanguageLabel } from "./LanguageLabel";
import type { TextPreview } from "./TextPreview";

export type PaletteContext = { appName: string | null, intent: IntentKind | null, subtype: IntentSubtype | null, language: LanguageLabel | null, languageName: string | null, selection: TextPreview | null, field: TextPreview | null, fieldTruncated: boolean, clipboard: ClipboardPreview | null, contextActions: Array<ContextAction>, hasApiKey: boolean, cloudEnabled: boolean, canInsert: boolean, };
