// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteSource } from "./PaletteSource";
import type { TransformAction } from "./TransformAction";

export type PaletteRunRequest = { action: TransformAction, source: PaletteSource, };
