// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyMode } from "./ApplyMode";

export type PaletteApplyRequest = { text: string, mode: ApplyMode, };
