// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceStats = { avgLatencyMs: number | null, medianLatencyMs: number | null, p95LatencyMs: number | null, completionAvgLatencyMs: number | null, completionMedianLatencyMs: number | null, classificationAvgLatencyMs: number | null, classificationMedianLatencyMs: number | null, failedRequests: number, 
/**
 * HTTP 429 responses, including ones Mote retried successfully.
 */
rateLimitEvents: number, timeouts: number, cancelled: number, errorRate: number, };
