// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeriodSummary = { requests: number, successful: number, failed: number, rateLimited: number, timeouts: number, cancelled: number, inputTokens: number, outputTokens: number, totalTokens: number, estimatedCostUsd: number, 
/**
 * False when some usage could not be priced (unknown model).
 */
costComplete: boolean, avgLatencyMs: number | null, 
/**
 * Failed / (requests − cancelled).
 */
errorRate: number, };
