// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionState } from "./PermissionState";

/**
 * Permissions and input-security state relevant to Mote.
 */
export type PermissionStatus = { accessibility: PermissionState, 
/**
 * macOS Secure Event Input is active (a password field or a secure
 * terminal has focus somewhere); Mote must not observe or type.
 */
secureInputActive: boolean, };
