// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of an OS permission.
 */
export type PermissionState = "granted" | "denied" | "not_required" | "unknown";
