// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionPeriod } from "./RetentionPeriod";

export type PrivacySettings = { 
/**
 * Allow sending text to the cloud AI provider at all.
 */
cloudAiEnabled: boolean, observeApplications: boolean, observeText: boolean, observeClipboard: boolean, contextRetention: RetentionPeriod, };
