// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnhanceStyle } from "./EnhanceStyle";

export type PromptSettings = { enhancementEnabled: boolean, 
/**
 * Show a small "Enhance prompt" hint when Mote detects a prompt; Tab on it
 * enhances the prompt in place.
 */
showHint: boolean, 
/**
 * The style used when enhancing from the hint.
 */
defaultStyle: EnhanceStyle, };
