// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptSettings = { enhancementEnabled: boolean, 
/**
 * Show a small "Enhance prompt" hint when Mote detects a prompt.
 */
showHint: boolean, };
