// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthReport } from "./HealthReport";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type ProviderStatus = { provider: string, displayName: string, hasApiKey: boolean, 
/**
 * Last four characters of the key, e.g. "…4Kcw".
 */
keyHint: string | null, baseUrl: string, health: HealthReport | null, limits: RateLimitSnapshot | null, unavailableModels: Array<string>, };
