// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroqSettings } from "./GroqSettings";
import type { ProviderKind } from "./ProviderKind";

export type ProviderSettings = { active: ProviderKind, groq: GroqSettings, };
