// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureUsage } from "./FeatureUsage";
import type { ModelUsage } from "./ModelUsage";
import type { PerformanceStats } from "./PerformanceStats";
import type { PeriodSummary } from "./PeriodSummary";
import type { TopFeature } from "./TopFeature";

/**
 * Feature, model and performance breakdowns for one time range.
 */
export type RangeBreakdown = { summary: PeriodSummary, byFeature: Array<FeatureUsage>, byModel: Array<ModelUsage>, performance: PerformanceStats, topFeature: TopFeature | null, };
