// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rate-limit state reported by the provider in response headers.
 */
export type RateLimitSnapshot = { 
/**
 * For Groq: requests per day.
 */
requestsLimit: number | null, requestsRemaining: number | null, requestsResetSecs: number | null, 
/**
 * For Groq: tokens per minute.
 */
tokensLimit: number | null, tokensRemaining: number | null, tokensResetSecs: number | null, observedAt: string, };
