// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle in screen coordinates.
 *
 * On macOS these are logical points with the origin at the top-left of the
 * primary display; on Windows they are physical pixels. See [`CoordinateSpace`].
 */
export type Rect = { x: number, y: number, width: number, height: number, };
