// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";
import type { UsageStatus } from "./UsageStatus";

/**
 * The latest request outcome, for diagnostics. Contains no content.
 */
export type RequestOutcome = { feature: Feature, model: string, status: UsageStatus, errorKind: string | null, latencyMs: number, at: string, message: string | null, };
