// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long context metadata is kept on disk.
 */
export type RetentionPeriod = "off" | "one_hour" | "one_day" | "one_week";
