// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SeriesPoint = { 
/**
 * `2026-10-07` for daily points, `14:00` for hourly points.
 */
label: string, requests: number, failed: number, inputTokens: number, outputTokens: number, totalTokens: number, estimatedCostUsd: number, avgLatencyMs: number | null, };
