// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionSettings } from "./CompletionSettings";
import type { ContextSettings } from "./ContextSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { KeyboardSettings } from "./KeyboardSettings";
import type { PrivacySettings } from "./PrivacySettings";
import type { PromptSettings } from "./PromptSettings";
import type { ProviderSettings } from "./ProviderSettings";
import type { UsageSettings } from "./UsageSettings";
import type { WritingSettings } from "./WritingSettings";

export type Settings = { version: number, general: GeneralSettings, provider: ProviderSettings, completion: CompletionSettings, writing: WritingSettings, prompts: PromptSettings, context: ContextSettings, privacy: PrivacySettings, usage: UsageSettings, keyboard: KeyboardSettings, };
