// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validation failure for one settings field.
 */
export type SettingsError = { field: string, message: string, };
