// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureGroup } from "./FeatureGroup";

export type TopFeature = { group: FeatureGroup, share: number, };
