// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAction } from "./ContextAction";
import type { EnhanceStyle } from "./EnhanceStyle";

/**
 * A text transformation requested by the user.
 */
export type TransformAction = { "kind": "fix_spelling_grammar" } | { "kind": "improve_writing" } | { "kind": "rewrite" } | { "kind": "professional" } | { "kind": "casual" } | { "kind": "clearer" } | { "kind": "concise" } | { "kind": "enhance_prompt", style: EnhanceStyle, } | { "kind": "custom_enhance", instruction: string, } | { "kind": "create_prompt" } | { "kind": "summarize" } | { "kind": "explain" } | { "kind": "translate", target: string, } | { "kind": "continue_writing" } | { "kind": "use_context", action: ContextAction, };
