// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the updater stands.
 */
export type UpdateState = { "state": "idle" } | { "state": "checking" } | { "state": "up_to_date" } | { "state": "downloading", version: string, } | { "state": "ready", version: string, } | { "state": "failed", message: string, };
