// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateState } from "./UpdateState";

export type UpdateStatus = { currentVersion: string, state: UpdateState, };
