// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageSettings = { 
/**
 * Record local usage statistics (metadata only).
 */
analyticsEnabled: boolean, 
/**
 * Days of usage history to keep.
 */
retentionDays: number, };
