// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodSummary } from "./PeriodSummary";
import type { RangeBreakdown } from "./RangeBreakdown";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";
import type { SeriesPoint } from "./SeriesPoint";

export type UsageDashboard = { generatedAt: string, today: PeriodSummary, week: PeriodSummary, month: PeriodSummary, last30Days: PeriodSummary, 
/**
 * Breakdowns for today, so one range filter can scope a whole view.
 */
breakdownToday: RangeBreakdown, 
/**
 * Breakdowns for the last 30 days.
 */
breakdown30d: RangeBreakdown, 
/**
 * One point per day for the last 30 days (oldest first).
 */
daily: Array<SeriesPoint>, 
/**
 * One point per hour for today.
 */
hourly: Array<SeriesPoint>, 
/**
 * Rate limits most recently reported by the provider (provider usage).
 */
providerLimits: RateLimitSnapshot | null, 
/**
 * Models with usage but no known price.
 */
unpricedModels: Array<string>, };
