// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final outcome of a logical request.
 */
export type UsageStatus = "success" | "error" | "rate_limited" | "timeout" | "cancelled";
