// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageDashboard } from "./UsageDashboard";

export type UsageResponse = { dashboard: UsageDashboard, suggestionsToday: { shown: number, accepted: number, dismissed: number }, suggestions30d: { shown: number, accepted: number, dismissed: number }, analyticsEnabled: boolean, };
