// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WritingSettings = { enabled: boolean, 
/**
 * Local, offline spelling suggestions (no tokens).
 */
spelling: boolean, 
/**
 * Ask the writing model to fix grammar when a sentence looks wrong.
 */
aiGrammar: boolean, 
/**
 * Words the user told Mote to accept (lowercase).
 */
ignoredWords: Array<string>, };
