//! The general pasteboard.
//!
//! Content marked by the copying application as concealed or transient
//! (`org.nspasteboard.ConcealedType`, used by password managers) is never read.
//! Text Mote writes for paste-to-insert is marked transient so clipboard
//! managers do not record it.

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;

use mote_core::platform::PlatformError;
use mote_core::text::head_chars;

const CONCEALED: &str = "org.nspasteboard.ConcealedType";
const TRANSIENT: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";

/// Pasteboard types that carry plain text only.
const PLAIN_TEXT_TYPES: &[&str] =
    &["public.utf8-plain-text", "public.utf16-plain-text", "public.utf16-external-plain-text", "NSStringPboardType"];

fn types() -> Vec<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.types().map(|types| types.iter().map(|t| t.to_string()).collect()).unwrap_or_default()
}

pub fn change_count() -> u64 {
    u64::try_from(NSPasteboard::generalPasteboard().changeCount()).unwrap_or(0)
}

/// Reads plain text, unless the content is marked concealed or transient.
pub fn read_text(max_chars: usize) -> Result<Option<String>, PlatformError> {
    let types = types();
    if types.iter().any(|t| t == CONCEALED || t == TRANSIENT) {
        return Ok(None);
    }
    let pasteboard = NSPasteboard::generalPasteboard();
    // SAFETY: reading a framework-provided constant.
    let string_type = unsafe { NSPasteboardTypeString };
    Ok(pasteboard.stringForType(string_type).map(|s| head_chars(&s.to_string(), max_chars).to_string()))
}

/// Whether the clipboard holds anything a plain-text round trip would lose.
pub fn has_non_text() -> bool {
    types().iter().any(|t| {
        !PLAIN_TEXT_TYPES.contains(&t.as_str())
            && !t.starts_with("org.nspasteboard.")
            && !t.starts_with("dyn.")
            && t != AUTO_GENERATED
    })
}

/// Replaces the clipboard with `text` (marked transient). Returns the new change count.
pub fn write_text(text: &str) -> Result<u64, PlatformError> {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    // SAFETY: reading a framework-provided constant.
    let string_type = unsafe { NSPasteboardTypeString };
    if !pasteboard.setString_forType(&NSString::from_str(text), string_type) {
        return Err(PlatformError::Failed("could not write to the clipboard".into()));
    }
    let transient = NSString::from_str(TRANSIENT);
    pasteboard.setString_forType(&NSString::from_str(""), &transient);
    Ok(change_count())
}
